import { SmokeTestAnalysis } from "./types";

export function generateMarkdownReport(analysis: SmokeTestAnalysis, originalIdea: string): string {
  return `# 🚀 SideHustle Smoke-Test: ${analysis.projectTitle}

> **"${analysis.tagline}"**
> 
> *This analysis was generated by SideHustle Smoke-Test — built for the #DevWeekend challenge.*

---

## 📊 Passion vs. Feasibility Matrix

- **Feasibility Score:** \`${analysis.feasibilityScore}/100\`
- **Passion Multiplier Required:** \`${analysis.passionMultiplier}/100\`
- **Market Demand Score:** \`${analysis.marketData.demandScore}/100\`

### 💡 The 2 A.M. Verdict
${analysis.analysisSummary}

---

## 🎯 Beachhead Market & Target Audience

- **Primary Target Audience:** ${analysis.marketData.targetAudienceSize}
- **Relevant Market Trends:**
${analysis.marketData.marketTrends.map(trend => `  - ${trend}`).join("\n")}

---

## ⚔️ Competitor Landscape & Differentiation

| Competitor / Status Quo | Core Strength | Core Weakness / Opportunity | Our 10x Differentiation Angle |
| :--- | :--- | :--- | :--- |
${analysis.competitors.map(c => `| **${c.name}** | ${c.strength} | ${c.weakness} | *${c.differentiationAngle}* |`).join("\n")}

---

## 🏗️ Technical Architecture Blueprint

- **Recommended Tech Stack:** ${analysis.techArchitecture.recommendedStack.join(" • ")}
- **Development Complexity:** \`${analysis.techArchitecture.developmentComplexity}\`
- **Estimated Build Time:** \`${analysis.techArchitecture.estimatedBuildTime}\`

### Architecture Overview
${analysis.techArchitecture.architectureOverview}

### ⚠️ Key Technical Risks & Bottlenecks
${analysis.techArchitecture.keyRisks.map(risk => `- ${risk}`).join("\n")}

---

## 💰 Monetization Strategies

${analysis.monetization.map(m => `### 💵 ${m.model}
- **How it works:** ${m.description}
- **Revenue Potential:** \`${m.revenuePotential}\`
- **Setup Difficulty:** \`${m.difficulty}\`
`).join("\n")}

---

## 🗺️ Lean Growth Roadmap

${analysis.growthRoadmap.map(r => `### 📍 ${r.phase} (Timeline: ${r.timeline})
${r.actions.map(action => `- [ ] ${action}`).join("\n")}
`).join("\n")}

---

## 🤔 Tough Reality Check Questions

Before spending money on domains or days on boilerplate setup, ask yourself:
${analysis.realityCheckQuestions.map((q, idx) => `${idx + 1}. **${q}**`).join("\n")}

---

*Original 2 A.M. Idea Input:*
*"${originalIdea}"*
`;
}

export const EXAMPLE_IDEAS = [
  {
    title: "SaaS Coffee optimal temperature alert API",
    idea: "A smart thermometer sticker on your mug that connects to a local server. When your coffee hits the perfect drinking window (between 130°F and 140°F), it triggers a webhooks API to send you a Slack notification or run a custom terminal command so you never drink lukewarm coffee again.",
    audience: "Caffeine-addicted Software Engineers & Tech Pros working remotely",
    budget: "Minimal - under $50 for prototyping",
    timeCommitment: "Weekend project"
  },
  {
    title: "GitHub commits to plant-watering dispenser",
    idea: "An automated physical plant watering system triggered by git commits. If you don't commit code to your side projects for 48 hours, a physical raspberry pi pump dispenses vinegar instead of water, slowly threatening your desk plant. Ultimate gamified motivation for devs.",
    audience: "Indie hackers, developers with ADHD, plant-loving coders",
    budget: "Medium (requires raspberry pi, small water pump)",
    timeCommitment: "Saturdays only (5 hours/week)"
  },
  {
    title: "Niche developer job board with zero jargon",
    idea: "A job board where posting a job requires answering 5 direct technical questions: 'What exact framework version do you use?', 'Is there an actual on-call rotation?', 'What is the absolute maximum budget?', 'What is the legacy codebase percentage?', and 'How long does the average build take?'. No recruitment fluff, pure facts.",
    audience: "Disillusioned Senior Developers seeking realistic roles",
    budget: "Free tier hosting ($0)",
    timeCommitment: "2 hours per night"
  }
];

export const MOCK_ANALYSIS_RESULT: SmokeTestAnalysis = {
  projectTitle: "GitHub Commits to Plant-Watering Dispenser",
  tagline: "Gamify your daily streaks with high-stakes botanical jeopardy.",
  feasibilityScore: 78,
  passionMultiplier: 92,
  analysisSummary: "Look, we've all been there: you need motivation. But physically threatening a real, living houseplant with vinegar over a broken git streak is a brilliantly chaotic, high-excitement idea. Technically, it is very feasible since Raspberry Pi pumps and GitHub webhooks are well-documented. However, the physical hardware requirement means shipping actual units if you want to monetize, which is a major logistical hurdle. It is highly engaging, but will probably end up as a viral social media post rather than a venture-backed SaaS. We love it.",
  marketData: {
    targetAudienceSize: "Indie hackers, developer influencers, and hardware enthusiasts with desk plants.",
    marketTrends: [
      "Gamified developer productivity tools (e.g. Habitica, code-streak widgets) are gaining strong viral traction.",
      "Hardware-software DIY kits (e.g., Raspberry Pi, ESP32) remain highly popular but suffer from component cost inflation.",
      "Tech-influencer culture on YouTube/TikTok is constantly starved for quirky physical-digital contraptions to build in public."
    ],
    demandScore: 65
  },
  competitors: [
    {
      name: "Habitica",
      strength: "Mature gamification system, large user base, handles multiple habit tracking types.",
      weakness: "Purely virtual, lack of real physical consequences, does not integrate natively with physical desk hardware.",
      differentiationAngle: "High physical stakes! Real water or real vinegar, directly responding to actual Git hooks in real-time."
    },
    {
      name: "Smart plant watering kits (Elegoo, etc.)",
      strength: "Inexpensive, widely available, easy to buy on Amazon.",
      weakness: "Completely manual schedule, no smart developer integrations, no developer humor or gamification.",
      differentiationAngle: "Integrates directly with Git repositories; acts as a developer motivation accessory instead of a smart home tool."
    },
    {
      name: "Github Profile Green Grass Widgets",
      strength: "Directly embedded in standard developer workflow, visible in public profile.",
      weakness: "Purely aesthetic, easy to fake with automated script commits, lacks any physical reality.",
      differentiationAngle: "Physical physical presence on your physical desk. No faking the plant's health."
    }
  ],
  techArchitecture: {
    recommendedStack: [
      "Vite + React (Frontend)",
      "Next.js / Express (Webhook receiver server)",
      "Node-RED or simple Python script (Raspberry Pi runner)",
      "Tailwind CSS (Dashboard)"
    ],
    architectureOverview: "A lightweight server hosts a webhook receiver. GitHub triggers a push event which sends a request to your server. The server verifies if a push has happened today, updates an database, and broadcasts a message to the Raspberry Pi over a secure lightweight WebSocket or MQTT client. The Pi executes a small GPIO pump script to either water or pause.",
    developmentComplexity: "Medium (Hardware integration & Webhook hosting)",
    estimatedBuildTime: "2-3 weeks",
    keyRisks: [
      "Network stability: Raspberry Pi losing local Wi-Fi connection, leading to dry plants or unwatered emergencies.",
      "Power management: Making sure the physical water pump doesn't short circuit or overflow the desk workspace.",
      "GitHub webhook delivery failure or spoofed commits bypasses."
    ]
  },
  monetization: [
    {
      model: "SaaS Dashboard + DIY Hardware Guide",
      description: "Provide the software dashboard, webhooks integration, and a comprehensive step-by-step DIY guide for free, charging $5/month for SMS/Discord plant emergency notifications, streaks history, and multi-repo support.",
      revenuePotential: "Low",
      difficulty: "Easy"
    },
    {
      model: "All-in-One Dev-Plant Kit (Physical eCommerce)",
      description: "Ship a beautiful pre-assembled premium wooden planter box containing the pump, custom sensors, and ESP32 chip. It arrives ready to plug-and-play. Price: $79.99.",
      revenuePotential: "High",
      difficulty: "Hard"
    }
  ],
  growthRoadmap: [
    {
      phase: "Phase 1: Build in Public & DIY Guide",
      timeline: "Week 1-2",
      actions: [
        "Create a simple landing page displaying a video of your personal prototype watering a plant.",
        "Post a thread on X/Twitter and Reddit (/r/baking, /r/raspberrypi) showcasing the extreme vinegar stakes.",
        "Collect emails from devs who want the open-source DIY blueprint."
      ]
    },
    {
      phase: "Phase 2: Open Source release & Dashboard MVP",
      timeline: "Week 3-4",
      actions: [
        "Deploy the open-source firmware and step-by-step assembly guide on GitHub.",
        "Launch the free tier hosted webhook dashboard to easily configure streaks and hooks.",
        "Analyze email capture rate and feedback from early DIY adopters."
      ]
    },
    {
      phase: "Phase 3: hardware Pre-orders",
      timeline: "Week 5-6",
      actions: [
        "Design a simplified custom PCB and wood box enclosing the kit.",
        "Add a 'Pre-Order physical kit' button to your landing page with a target goal of 100 units.",
        "Reach out to tech newsletter writers (TLDR, HackerNews, ByteByteGo) to feature the build story."
      ]
    }
  ],
  realityCheckQuestions: [
    "Are you willing to actually handle physical inventory, shipping, and supplier delays, or do you just want an excuse to play with a Raspberry Pi?",
    "Will you eventually get annoyed at GitHub webhooks and just automate a dummy repository push script to avoid killing your plant with vinegar?",
    "Does your target market actually want to buy a $80 hardware accessory, or do they just want to upvote it on HackerNews and leave?"
  ]
};
