name: Checking Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # 💡 Removed 18.x since @tailwindcss/oxide and Vite require >= 20.x
        node-version: [20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # Optional tip: caching dependencies speeds up your builds!

    - name: Build
      run: |
        npm install && npm run build
